### ISSUE TITLE
Make ProActive Connector compatible with scilab 5.5

### ISSUE THREAD

**Issue by activeeon-bot** [ow2-proactive/connector-matlab-scilab#242]
<a href="https://jira.activeeon.com/browse/MSC-250" title="MSC-250">Original issue</a> created by <a href="mailto:fabien.viale_AT_activeeon.com">Fabien Viale</a> on 15, Apr 2014 at 14:21 PM - MSC-250

<hr />
- Scilab 5.5 includes JIMS instead of a ATOMS module
- JIMS behaviour and semantic is different : java array indexes now start from 1 instead of 0 and autoUnwrap transform lists into arrays.

**Comment by mbenguig** [comment]
Fix Support for Scilab 5.5 and more #287
