### ISSUE TITLE
Matlab/Scilab task output not correctly retrieved

### ISSUE THREAD

**Issue by fviale** [ow2-proactive/connector-matlab-scilab#277]
When executing a matlab task, no matlab worker output is gathered by the task. 

By analysing the log files in temp directory (MatlabStart..., MatlabExecutable...), the output is there, but it's not read by the task.

**Comment by mbenguig** [comment]
Still not fixed with scilab. Moreover, in case of multi task jobs, tasks do not properly gather Matlab workers outputs (same output displayed for different tasks, ...)
